module.exports = {

  BUSCAR_SINIESTRO_VEHICULO: `
      SELECT COUNT(1) AS status, L.DESCRIP AS mensaje
      FROM ACSELX.DATOS_PARTICULARES DP
               INNER JOIN ACSELX.POLIZA POL ON POL.IDEPOL = DP.IDEPOL
               INNER JOIN ACSELX.CERTIFICADO CERT ON CERT.IDEPOL = POL.IDEPOL
               INNER JOIN ACSELX.SINIESTRO SIN ON (SIN.IDEPOL = CERT.IDEPOL AND SIN.NUMCERT = CERT.NUMCERT)
               INNER JOIN ACSELX.EST_SIN EST ON EST.IDESIN = SIN.IDESIN
               INNER JOIN ACSELX.LVAL L ON (L.CODLVAL = CONCAT(EST.CODEST, EST.VALEST) AND L.TIPOLVAL = 'SINPERTL')
      WHERE POL.STSPOL NOT IN ('ANU', 'EXC')
        AND CERT.STSCERT NOT IN ('ANU', 'EXC')
        AND DP.CODCRIT = :tipo
        AND DP.VALTRASF = :valor
      GROUP BY L.DESCRIP
      LIMIT 1;
  `

};
